interface eth0 {
    AdvRASrcAddress {
        fe80::2;
    };
    AdvSendAdvert on;
    MinRtrAdvInterval 3;
    MaxRtrAdvInterval 4;
    AdvDefaultLifetime 12;
    AdvDefaultPreference low;
    prefix 2001:db8:10::/64 {
        AdvOnLink on;
        AdvAutonomous on;
        AdvValidLifetime 300;
        AdvPreferredLifetime 120;
    };
};
